Str = input("Enter a String (innclude both Uppercase and Lowercase at any position : ")
print("Capitalized first letter : ",Str.capitalize())
print("Lower case string : ",Str.casefold())
print("Centered string : ",Str.center(20, '*'))
Str1 = input("Enter value to be counted for occurence : ")
print("Count of ",Str1," : ",Str.count(Str1))
print("Encoded String : ",Str.encode())
Str2 = input("Enter value to find if it ends with it : ")
x1 = Str.endswith(Str2)
print(x1)
print("Expanded Tabs : ",Str.expandtabs())
Str3 = input("Enter value to be found : ")
print(Str3," found at : ",Str.find(Str3))
#index is similar to find
x2 = Str.isalnum()
print("Entered String is alphanumeric : ",x2)
x3 = Str.isalpha()
print("Entered String is alpha : ",x3)
x4 = Str.isdecimal()
print("Entered Spring has decimal alphacodes : ",x4)
x5 = Str.isdigit()
print("Enter string has all digits : ",x5)
x6 = Str.isidentifier()
print("String is an identifier : ",x6)
x7 = Str.islower()
print("String consists of all lower characters : ",x7)
x8 = Str.isprintable()
print("All string characters are printable : ",x8)
x9 = Str.isspace()
print("All string characters are whitespaces : ",x9)
x10 = Str.istitle()
print("String follows the rule of title : ",x10)
x11 = Str.isupper()
print("All string characters are uppercase : ",x11)
print("Left justified version of the string : ",Str.ljust(50, "*"))
print("Lower case: ",Str.lower())
print("Left trim version : ",Str.lstrip())
print("String parted to three parts : ",Str.partition("r"))
x12 = input("Enter value to replace : ")
x13 = input("Enter value to be replaced : ")
print("Repacled string : ",Str.replace(x13, x12))
#rfind same as rindex
x14 = input("Enter value to be searched : ")
print("Last position where it was found : ",Str.rfind(x14))
print("Right justified version of the string : ",Str.rjust(50, "*"))
print("Tuple of string parted into three parts : ",Str.rpartition("r"))
print("Right trim version of the string : ",Str.rstrip())
#rsplit same as split
x15 = input("Enter value at which string is to be seaprated : ")
print("List of splitted String : ",Str.split(x15))
x16 = input("Enter value to check if the string starts with it : ")
x17 = Str.startswith(x16)
print = (x17)
print = ("String splitted at line break : ",Str.splitlines())
print = ("Trimmed version of String : ",Str.strip())
print = ("Swapped cases : ",Str.swapcase())
print = ("Converting first character of each word to Upper case : ",Str.title())
print = ("Filling the string with 2 0s at beginning : ",Str.zfill(2))
